language: java
jdk: openjdk8
services:
  - docker
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  - NODE_OPTIONS=--max_old_space_size=4096 IMAGE_NAME=porscheinformatik/zanata-server
install: true
script:
  - ./mvnw -e -V --builder singlethreaded -batch-mode -Dstyle.color=never --update-snapshots -Doptimise -Dkotlin.compiler.incremental=false -DskipFuncTests -DskipArqTests -Dappserver=wildfly8 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install
  - cp ./server/zanata-war/target/zanata-*.war ./server/docker/zanata.war
  - docker build -t $IMAGE_NAME ./server/docker
deploy:
  - provider: script
    script: bash docker_push master && cp .travis-settings.xml $HOME/.m2/settings.xml && mvn -B deploy -DskipTests -pl :zanata-cli,:zanata-maven-plugin -am
    on:
      branch: master
  - provider: script
    script: bash docker_push ${TRAVIS_TAG#v}
    on:
      tags: true
